version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "80:3000"
      - "443:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env.${NODE_ENV:-production}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
