version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        - NODE_ENV=development
    ports:
      - "80:3000"
      - "443:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - VITE_TELEGRAM_BOT_USERNAME=${VITE_TG_BOT_NAME:-NoteGrafana_bot}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env.development
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
